/**
 * Routes and browser-WS verbs deliberately NOT exposed over MCP (change:
 * expand-mcp-tiered-surface, D6). Each entry carries a reason; the completeness
 * test fails a route/verb that is neither bound in the manifest nor listed here.
 */
export interface DenylistEntry {
  /** A route PATH (exact) or path PREFIX (trailing `/`), or a WS verb name. */
  pattern: string;
  reason: string;
}

export const DENYLIST: readonly DenylistEntry[] = [
  { pattern: "/api/auth/", reason: "auth internals" },
  { pattern: "/api/model-proxy/", reason: "model-proxy; host-local only" },
  { pattern: "/api/provider-auth/", reason: "provider auth + API-key material" },
  { pattern: "/api/electron/", reason: "Electron-only" },
  { pattern: "/api/mcp-client/", reason: "MCP client config; UI-only" },
  { pattern: "/api/live-server/", reason: "live-server preview UI" },
  { pattern: "/api/node/", reason: "node runtime UI" },
  { pattern: "/api/preferences/", reason: "UI preferences" },
  { pattern: "/api/grammar/", reason: "UI-only" },
  { pattern: "/api/kb/", reason: "kb engine admin" },
  { pattern: "/api/cost-estimator/", reason: "billing telemetry UI" },
  { pattern: "/api/flows-anthropic-bridge/", reason: "bridge diagnostics" },
  { pattern: "/api/plugins/blackhole/", reason: "plugin-internal" },
  { pattern: "/api/plugins/hermes-memory/", reason: "plugin-internal config" },
  { pattern: "/api/plugins/flows/", reason: "plugin-internal" },
  { pattern: "/api/tools/", reason: "tool-registry UI" },
  { pattern: "/api/ws-ticket", reason: "transport credential" },
  { pattern: "/api/pair/challenge", reason: "pairing ceremony" },
  { pattern: "/api/pair/payload", reason: "pairing ceremony" },
  { pattern: "/api/pair/poll", reason: "pairing ceremony" },
  { pattern: "/api/pair/redeem", reason: "pairing ceremony" },
  { pattern: "/api/pair/approve", reason: "pairing ceremony" },
  { pattern: "/api/discover-servers", reason: "fleet discovery UI" },
  { pattern: "/api/known-servers", reason: "fleet discovery UI" },
  { pattern: "/api/pi/runtime", reason: "pi runtime UI" },
  { pattern: "/api/tools", reason: "tool-registry UI" },
  { pattern: "/api/open-in-system", reason: "UI-only" },
  { pattern: "/api/reveal-in-file-manager", reason: "UI-only" },
  { pattern: "/api/pinned-dirs", reason: "UI-only" },
  { pattern: "/api/favorite-models", reason: "UI-only" },
  { pattern: "/api/custom-event-groups", reason: "UI-only" },
  { pattern: "/api/canvas-types", reason: "UI-only" },
  { pattern: "/api/diagram/render", reason: "UI-only" },
  { pattern: "/api/host-gate", reason: "host admission internals" },
  { pattern: "/api/network-interfaces", reason: "fleet enumeration UI" },
  { pattern: "/api/auto-name-outcomes", reason: "UI diagnostics" },
  { pattern: "/api/spawn-failures", reason: "UI diagnostics" },
  { pattern: "/api/quota", reason: "UI quota widget" },
  { pattern: "/api/sessions", reason: "duplicate-of:list_sessions" },
  { pattern: "/api/session/spawn", reason: "duplicate-of:spawn_session" },
  { pattern: "/api/session/:id/prompt", reason: "duplicate-of:send_prompt" },
  { pattern: "/api/session/:id/abort", reason: "duplicate-of:abort" },
  { pattern: "abort", reason: "duplicate-of:abort" },
  { pattern: "accept_replace_proposal", reason: "not-advertised: UI-only, transport, or bridge-internal verb" },
  { pattern: "add_folder_to_workspace", reason: "not-advertised: UI-only, transport, or bridge-internal verb" },
  { pattern: "architect_prompt_response", reason: "not-advertised: UI-only, transport, or bridge-internal verb" },
  { pattern: "archive_session", reason: "duplicate-of:archive_session" },
  { pattern: "attach_proposal", reason: "duplicate-of:attach_proposal" },
  { pattern: "browser_relay_input", reason: "not-advertised: UI-only, transport, or bridge-internal verb" },
  { pattern: "browser_relay_subscribe", reason: "not-advertised: UI-only, transport, or bridge-internal verb" },
  { pattern: "browser_relay_unsubscribe", reason: "not-advertised: UI-only, transport, or bridge-internal verb" },
  { pattern: "clear_followup_entries", reason: "not-advertised: UI-only, transport, or bridge-internal verb" },
  { pattern: "close_inline_terminal", reason: "not-advertised: UI-only, transport, or bridge-internal verb" },
  { pattern: "create_terminal", reason: "not-advertised: UI-only, transport, or bridge-internal verb" },
  { pattern: "create_workspace", reason: "not-advertised: UI-only, transport, or bridge-internal verb" },
  { pattern: "delete_workspace", reason: "not-advertised: UI-only, transport, or bridge-internal verb" },
  { pattern: "detach_proposal", reason: "duplicate-of:detach_proposal" },
  { pattern: "dismiss_replace_proposal", reason: "not-advertised: UI-only, transport, or bridge-internal verb" },
  { pattern: "extension_ui_response", reason: "duplicate-of:extension_ui_response" },
  { pattern: "favorite_model", reason: "not-advertised: UI-only, transport, or bridge-internal verb" },
  { pattern: "fetch_content", reason: "not-advertised: UI-only, transport, or bridge-internal verb" },
  { pattern: "flow_control", reason: "duplicate-of:flow_control" },
  { pattern: "flow_management", reason: "not-advertised: UI-only, transport, or bridge-internal verb" },
  { pattern: "force_kill", reason: "duplicate-of:force_kill" },
  { pattern: "kill_process", reason: "duplicate-of:kill_process" },
  { pattern: "kill_terminal", reason: "not-advertised: UI-only, transport, or bridge-internal verb" },
  { pattern: "list_files", reason: "not-advertised: UI-only, transport, or bridge-internal verb" },
  { pattern: "list_sessions", reason: "duplicate-of:list_sessions" },
  { pattern: "move_folder_to_workspace", reason: "not-advertised: UI-only, transport, or bridge-internal verb" },
  { pattern: "open_inline_terminal", reason: "not-advertised: UI-only, transport, or bridge-internal verb" },
  { pattern: "openspec_bulk_archive", reason: "not-advertised: UI-only, transport, or bridge-internal verb" },
  { pattern: "openspec_get", reason: "not-advertised: UI-only, transport, or bridge-internal verb" },
  { pattern: "openspec_refresh", reason: "not-advertised: UI-only, transport, or bridge-internal verb" },
  { pattern: "pin_directory", reason: "not-advertised: UI-only, transport, or bridge-internal verb" },
  { pattern: "plugin_action", reason: "not-advertised: UI-only, transport, or bridge-internal verb" },
  { pattern: "plugin_config_write", reason: "not-advertised: UI-only, transport, or bridge-internal verb" },
  { pattern: "promote_followup_entry", reason: "not-advertised: UI-only, transport, or bridge-internal verb" },
  { pattern: "prompt_resync_request", reason: "not-advertised: UI-only, transport, or bridge-internal verb" },
  { pattern: "recovery_dismiss", reason: "not-advertised: UI-only, transport, or bridge-internal verb" },
  { pattern: "remove_folder_from_workspace", reason: "not-advertised: UI-only, transport, or bridge-internal verb" },
  { pattern: "remove_followup_entry", reason: "not-advertised: UI-only, transport, or bridge-internal verb" },
  { pattern: "remove_tag_globally", reason: "not-advertised: UI-only, transport, or bridge-internal verb" },
  { pattern: "rename_session", reason: "duplicate-of:rename_session" },
  { pattern: "rename_terminal", reason: "not-advertised: UI-only, transport, or bridge-internal verb" },
  { pattern: "rename_workspace", reason: "not-advertised: UI-only, transport, or bridge-internal verb" },
  { pattern: "reorder_pinned_dirs", reason: "not-advertised: UI-only, transport, or bridge-internal verb" },
  { pattern: "reorder_sessions", reason: "not-advertised: UI-only, transport, or bridge-internal verb" },
  { pattern: "reorder_workspace_folders", reason: "not-advertised: UI-only, transport, or bridge-internal verb" },
  { pattern: "reorder_workspaces", reason: "not-advertised: UI-only, transport, or bridge-internal verb" },
  { pattern: "request_commands", reason: "not-advertised: UI-only, transport, or bridge-internal verb" },
  { pattern: "request_models", reason: "not-advertised: UI-only, transport, or bridge-internal verb" },
  { pattern: "request_providers", reason: "not-advertised: UI-only, transport, or bridge-internal verb" },
  { pattern: "request_roles", reason: "not-advertised: UI-only, transport, or bridge-internal verb" },
  { pattern: "resume_session", reason: "duplicate-of:resume_session" },
  { pattern: "retry_session", reason: "duplicate-of:retry_session" },
  { pattern: "role_preset_delete", reason: "not-advertised: UI-only, transport, or bridge-internal verb" },
  { pattern: "role_preset_load", reason: "not-advertised: UI-only, transport, or bridge-internal verb" },
  { pattern: "role_preset_save", reason: "not-advertised: UI-only, transport, or bridge-internal verb" },
  { pattern: "role_remove", reason: "not-advertised: UI-only, transport, or bridge-internal verb" },
  { pattern: "role_set", reason: "not-advertised: UI-only, transport, or bridge-internal verb" },
  { pattern: "send_prompt", reason: "duplicate-of:send_prompt" },
  { pattern: "session_unview", reason: "not-advertised: UI-only, transport, or bridge-internal verb" },
  { pattern: "session_view", reason: "not-advertised: UI-only, transport, or bridge-internal verb" },
  { pattern: "sessions_page", reason: "not-advertised: UI-only, transport, or bridge-internal verb" },
  { pattern: "setSessionDisplayPrefs", reason: "not-advertised: UI-only, transport, or bridge-internal verb" },
  { pattern: "set_model", reason: "duplicate-of:set_model" },
  { pattern: "set_session_process_drawer", reason: "not-advertised: UI-only, transport, or bridge-internal verb" },
  { pattern: "set_thinking_level", reason: "duplicate-of:set_thinking_level" },
  { pattern: "set_workspace_collapsed", reason: "not-advertised: UI-only, transport, or bridge-internal verb" },
  { pattern: "shutdown", reason: "duplicate-of:shutdown" },
  { pattern: "spawn_session", reason: "duplicate-of:spawn_session" },
  { pattern: "stop_after_turn", reason: "duplicate-of:stop_after_turn" },
  { pattern: "subagent_resync_request", reason: "not-advertised: UI-only, transport, or bridge-internal verb" },
  { pattern: "subscribe", reason: "not-advertised: UI-only, transport, or bridge-internal verb" },
  { pattern: "ui_management", reason: "not-advertised: UI-only, transport, or bridge-internal verb" },
  { pattern: "unarchive_session", reason: "duplicate-of:unarchive_session" },
  { pattern: "unfavorite_model", reason: "not-advertised: UI-only, transport, or bridge-internal verb" },
  { pattern: "unpin_directory", reason: "not-advertised: UI-only, transport, or bridge-internal verb" },
  { pattern: "unsubscribe", reason: "not-advertised: UI-only, transport, or bridge-internal verb" },
  { pattern: "watch_files", reason: "not-advertised: UI-only, transport, or bridge-internal verb" },
  { pattern: "worktree_init_subscribe", reason: "not-advertised: UI-only, transport, or bridge-internal verb" },
  { pattern: "worktree_init_unsubscribe", reason: "not-advertised: UI-only, transport, or bridge-internal verb" },
];

/**
 * Whether a route path or WS verb is denylisted. A trailing `/` marks a path
 * PREFIX; otherwise the match is EXACT (so `/api/sessions` does not deny
 * `/api/sessions/archived`).
 */
export function isDenylisted(name: string): boolean {
  return DENYLIST.some((e) =>
    e.pattern.endsWith("/") ? name.startsWith(e.pattern) : name === e.pattern,
  );
}
