/**
 * Route → tier map (see change: expand-mcp-tiered-surface, design D1b/D7).
 *
 * ONE source of truth for the tier a REST route requires. Two consumers read
 * it: the server's REST tier gate (`auth/route-tier-gate.ts`) and the MCP
 * manifest's `rest` rows (their tool tier is the route's tier, or higher for
 * the sanctioned lifecycle actions). One definition, so the two surfaces cannot
 * disagree.
 *
 * Fail-closed: an UNLISTED route resolves to `operate`, the strongest tier.
 * The completeness test fails an /api route missing from this list, so an
 * untriaged route is a build failure rather than a silent `operate`.
 *
 * Scope: `/api/*` only. `/mcp`, `/auth/*` and `/v1/*` have their own
 * admission and are outside this map.
 */
import type { Tier } from "./tiers.js";

export interface RouteTierEntry {
  /** Uppercase HTTP method. */
  method: string;
  /** Fastify path PATTERN (e.g. `/api/session/:id/prompt`), not a concrete URL. */
  path: string;
  tier: Tier;
}

/**
 * Every `/api/*` route and its required tier.
 */
export const ROUTE_TIERS: readonly RouteTierEntry[] = [
  { method: "DELETE", path: "/api/config/auth/providers/:id", tier: "control" },
  { method: "DELETE", path: "/api/folders/goals/:id", tier: "control" },
  { method: "DELETE", path: "/api/folders/goals/:id/sessions/:sid", tier: "control" },
  { method: "DELETE", path: "/api/known-servers", tier: "operate" },
  { method: "DELETE", path: "/api/live-server/:id", tier: "operate" },
  { method: "DELETE", path: "/api/mcp-client/servers/:name", tier: "operate" },
  { method: "DELETE", path: "/api/model-proxy/api-keys/:id", tier: "control" },
  { method: "DELETE", path: "/api/openspec/groups/:id", tier: "control" },
  { method: "DELETE", path: "/api/paired-devices/:id", tier: "operate" },
  { method: "DELETE", path: "/api/plugins/automation", tier: "control" },
  { method: "DELETE", path: "/api/provider-auth/:provider", tier: "operate" },
  { method: "DELETE", path: "/api/sessions/archived/:id", tier: "control" },
  { method: "DELETE", path: "/api/tools/:name", tier: "control" },
  { method: "GET", path: "/api/apple-tools/status", tier: "observe" },
  { method: "GET", path: "/api/auth/diagnostics", tier: "operate" },
  { method: "GET", path: "/api/auto-name-outcomes", tier: "observe" },
  { method: "GET", path: "/api/browse", tier: "observe" },
  { method: "GET", path: "/api/browse/flags", tier: "observe" },
  { method: "GET", path: "/api/canvas-types", tier: "observe" },
  { method: "GET", path: "/api/config", tier: "operate" },
  { method: "GET", path: "/api/cost-estimator/telemetry", tier: "observe" },
  { method: "GET", path: "/api/custom-event-groups", tier: "observe" },
  { method: "GET", path: "/api/doctor", tier: "observe" },
  { method: "GET", path: "/api/events/:sessionId/:seq", tier: "observe" },
  { method: "GET", path: "/api/favorite-models", tier: "observe" },
  { method: "GET", path: "/api/file", tier: "observe" },
  { method: "GET", path: "/api/file/eml", tier: "observe" },
  { method: "GET", path: "/api/file/eml-attachment", tier: "observe" },
  { method: "GET", path: "/api/file/exists", tier: "observe" },
  { method: "GET", path: "/api/file/md-candidates", tier: "observe" },
  { method: "GET", path: "/api/file/md-read", tier: "observe" },
  { method: "GET", path: "/api/file/raw", tier: "observe" },
  { method: "GET", path: "/api/file/render", tier: "observe" },
  { method: "GET", path: "/api/file/rendered-pdf", tier: "observe" },
  { method: "GET", path: "/api/file/sheet", tier: "observe" },
  { method: "GET", path: "/api/file/tree", tier: "observe" },
  { method: "GET", path: "/api/flows-anthropic-bridge/status", tier: "observe" },
  { method: "GET", path: "/api/folders/goals", tier: "observe" },
  { method: "GET", path: "/api/git/branches", tier: "observe" },
  { method: "GET", path: "/api/git/changed-files", tier: "observe" },
  { method: "GET", path: "/api/git/head", tier: "observe" },
  { method: "GET", path: "/api/git/pull-requests", tier: "observe" },
  { method: "GET", path: "/api/git/status", tier: "observe" },
  { method: "GET", path: "/api/git/worktree/active-inits", tier: "observe" },
  { method: "GET", path: "/api/git/worktree/diff-stat", tier: "observe" },
  { method: "GET", path: "/api/git/worktree/init-status", tier: "observe" },
  { method: "GET", path: "/api/git/worktrees", tier: "observe" },
  { method: "GET", path: "/api/grammar/health", tier: "observe" },
  { method: "GET", path: "/api/grep", tier: "observe" },
  { method: "GET", path: "/api/health", tier: "observe" },
  { method: "GET", path: "/api/host-gate", tier: "operate" },
  { method: "GET", path: "/api/kb/config", tier: "observe" },
  { method: "GET", path: "/api/kb/stats", tier: "observe" },
  { method: "GET", path: "/api/known-servers", tier: "operate" },
  { method: "GET", path: "/api/live-server/list", tier: "operate" },
  { method: "GET", path: "/api/mcp-client/adapter", tier: "observe" },
  { method: "GET", path: "/api/mcp-client/effective", tier: "operate" },
  { method: "GET", path: "/api/mcp-client/schema", tier: "observe" },
  { method: "GET", path: "/api/model-proxy/api-keys", tier: "operate" },
  { method: "GET", path: "/api/model-proxy/diagnostics", tier: "operate" },
  { method: "GET", path: "/api/models", tier: "observe" },
  { method: "GET", path: "/api/network-interfaces", tier: "operate" },
  { method: "GET", path: "/api/node/installs", tier: "observe" },
  { method: "GET", path: "/api/openspec-archive", tier: "observe" },
  { method: "GET", path: "/api/openspec/config", tier: "observe" },
  { method: "GET", path: "/api/openspec/groups", tier: "observe" },
  { method: "GET", path: "/api/openspec/tasks", tier: "observe" },
  { method: "GET", path: "/api/openspec/update-status", tier: "observe" },
  { method: "GET", path: "/api/packages/installed", tier: "observe" },
  { method: "GET", path: "/api/packages/readme", tier: "observe" },
  { method: "GET", path: "/api/packages/recommended", tier: "observe" },
  { method: "GET", path: "/api/packages/search", tier: "observe" },
  { method: "GET", path: "/api/pair/payload", tier: "operate" },
  { method: "GET", path: "/api/pair/reachable-urls", tier: "operate" },
  { method: "GET", path: "/api/paired-devices", tier: "operate" },
  { method: "GET", path: "/api/pi-core/changelog", tier: "observe" },
  { method: "GET", path: "/api/pi-core/versions", tier: "observe" },
  { method: "GET", path: "/api/pi-resource-file", tier: "observe" },
  { method: "GET", path: "/api/pi-resources", tier: "observe" },
  { method: "GET", path: "/api/pi-retry", tier: "observe" },
  { method: "GET", path: "/api/pi/installs", tier: "observe" },
  { method: "GET", path: "/api/pinned-dirs", tier: "observe" },
  { method: "GET", path: "/api/plugins", tier: "observe" },
  { method: "GET", path: "/api/plugins/automation/actions", tier: "observe" },
  { method: "GET", path: "/api/plugins/automation/definition", tier: "observe" },
  { method: "GET", path: "/api/plugins/automation/git-capable", tier: "observe" },
  { method: "GET", path: "/api/plugins/automation/list", tier: "observe" },
  { method: "GET", path: "/api/plugins/automation/result", tier: "observe" },
  { method: "GET", path: "/api/plugins/automation/runs", tier: "observe" },
  { method: "GET", path: "/api/plugins/automation/trigger-kinds", tier: "observe" },
  { method: "GET", path: "/api/plugins/blackhole/config", tier: "operate" },
  { method: "GET", path: "/api/plugins/blackhole/session/:id", tier: "observe" },
  { method: "GET", path: "/api/plugins/blackhole/status", tier: "observe" },
  { method: "GET", path: "/api/plugins/flows/flow-inputs", tier: "observe" },
  { method: "GET", path: "/api/plugins/hermes-memory/config", tier: "operate" },
  { method: "GET", path: "/api/preferences/auto-name", tier: "observe" },
  { method: "GET", path: "/api/preferences/display", tier: "observe" },
  { method: "GET", path: "/api/preferences/worktree-auto-init", tier: "observe" },
  { method: "GET", path: "/api/provider-auth/device-status/:flowId", tier: "operate" },
  { method: "GET", path: "/api/provider-auth/handlers", tier: "operate" },
  { method: "GET", path: "/api/provider-auth/providers", tier: "operate" },
  { method: "GET", path: "/api/provider-auth/status", tier: "operate" },
  { method: "GET", path: "/api/providers", tier: "observe" },
  { method: "GET", path: "/api/quota", tier: "observe" },
  { method: "GET", path: "/api/roles", tier: "observe" },
  { method: "GET", path: "/api/session-change/:sessionId/:toolCallId", tier: "observe" },
  { method: "GET", path: "/api/session-diff", tier: "observe" },
  { method: "GET", path: "/api/session-file", tier: "observe" },
  { method: "GET", path: "/api/sessions", tier: "observe" },
  { method: "GET", path: "/api/sessions/:sessionId/attachments/:attachmentId", tier: "observe" },
  { method: "GET", path: "/api/sessions/:sessionId/retained-transcript", tier: "observe" },
  { method: "GET", path: "/api/sessions/:sessionId/tool-result/:toolCallId", tier: "observe" },
  { method: "GET", path: "/api/sessions/archived", tier: "observe" },
  { method: "GET", path: "/api/sessions/archived/:id", tier: "observe" },
  { method: "GET", path: "/api/spawn-failures", tier: "observe" },
  { method: "GET", path: "/api/tools", tier: "observe" },
  { method: "GET", path: "/api/tools/:name", tier: "observe" },
  { method: "GET", path: "/api/tunnel-readiness", tier: "observe" },
  { method: "GET", path: "/api/tunnel-status", tier: "observe" },
  { method: "GET", path: "/api/tunnel-status-detail", tier: "observe" },
  { method: "GET", path: "/api/tunnel/block-events", tier: "operate" },
  { method: "GET", path: "/api/tunnel/endpoints", tier: "operate" },
  { method: "PATCH", path: "/api/canvas-types", tier: "control" },
  { method: "PATCH", path: "/api/folders/goals/:id", tier: "control" },
  { method: "PATCH", path: "/api/openspec/groups/:id", tier: "control" },
  { method: "PATCH", path: "/api/preferences/auto-name", tier: "control" },
  { method: "PATCH", path: "/api/preferences/display", tier: "control" },
  { method: "PATCH", path: "/api/preferences/worktree-auto-init", tier: "control" },
  { method: "POST", path: "/api/browse/mkdir", tier: "control" },
  { method: "POST", path: "/api/config/plugins/:id", tier: "operate" },
  { method: "POST", path: "/api/diagram/render", tier: "control" },
  { method: "POST", path: "/api/discover-servers", tier: "operate" },
  { method: "POST", path: "/api/electron/reextract", tier: "operate" },
  { method: "POST", path: "/api/file/resolve-mention", tier: "observe" },
  { method: "POST", path: "/api/file/write", tier: "control" },
  { method: "POST", path: "/api/folders/goals", tier: "control" },
  { method: "POST", path: "/api/folders/goals/:id/sessions", tier: "control" },
  { method: "POST", path: "/api/git/checkout", tier: "control" },
  { method: "POST", path: "/api/git/commit", tier: "control" },
  { method: "POST", path: "/api/git/commit-draft", tier: "control" },
  { method: "POST", path: "/api/git/init", tier: "control" },
  { method: "POST", path: "/api/git/stash-pop", tier: "control" },
  { method: "POST", path: "/api/git/worktree", tier: "control" },
  { method: "POST", path: "/api/git/worktree/from-pr", tier: "control" },
  { method: "POST", path: "/api/git/worktree/init", tier: "control" },
  { method: "POST", path: "/api/git/worktree/merge", tier: "control" },
  { method: "POST", path: "/api/git/worktree/orphan-cleanup", tier: "control" },
  { method: "POST", path: "/api/git/worktree/pr", tier: "control" },
  { method: "POST", path: "/api/git/worktree/prune", tier: "control" },
  { method: "POST", path: "/api/git/worktree/push", tier: "control" },
  { method: "POST", path: "/api/git/worktree/remove", tier: "control" },
  { method: "POST", path: "/api/git/worktree/remove-batch", tier: "control" },
  { method: "POST", path: "/api/grammar/check", tier: "observe" },
  { method: "POST", path: "/api/kb/reindex", tier: "operate" },
  { method: "POST", path: "/api/known-servers", tier: "operate" },
  { method: "POST", path: "/api/live-server/start", tier: "operate" },
  { method: "POST", path: "/api/model-proxy/api-keys", tier: "operate" },
  { method: "POST", path: "/api/model-proxy/api-keys/:id/revoke", tier: "operate" },
  { method: "POST", path: "/api/model-proxy/refresh", tier: "operate" },
  { method: "POST", path: "/api/node/installs/select", tier: "operate" },
  { method: "POST", path: "/api/open-in-system", tier: "operate" },
  { method: "POST", path: "/api/openspec/config", tier: "control" },
  { method: "POST", path: "/api/openspec/groups", tier: "control" },
  { method: "POST", path: "/api/openspec/init", tier: "control" },
  { method: "POST", path: "/api/openspec/tasks/toggle", tier: "control" },
  { method: "POST", path: "/api/openspec/update", tier: "control" },
  { method: "POST", path: "/api/packages/check-updates", tier: "operate" },
  { method: "POST", path: "/api/packages/install", tier: "operate" },
  { method: "POST", path: "/api/packages/move", tier: "operate" },
  { method: "POST", path: "/api/packages/remove", tier: "operate" },
  { method: "POST", path: "/api/packages/reset-to-npm", tier: "operate" },
  { method: "POST", path: "/api/packages/update", tier: "operate" },
  { method: "POST", path: "/api/pair/approve", tier: "operate" },
  { method: "POST", path: "/api/pair/challenge", tier: "operate" },
  { method: "POST", path: "/api/pair/poll", tier: "operate" },
  { method: "POST", path: "/api/pair/redeem", tier: "operate" },
  { method: "POST", path: "/api/paired-devices", tier: "operate" },
  { method: "POST", path: "/api/pi-core/update", tier: "operate" },
  { method: "POST", path: "/api/pi/runtime", tier: "operate" },
  { method: "POST", path: "/api/plugins/:id/toggle", tier: "operate" },
  { method: "POST", path: "/api/plugins/automation/create", tier: "control" },
  { method: "POST", path: "/api/plugins/automation/run", tier: "control" },
  { method: "POST", path: "/api/plugins/automation/stop", tier: "control" },
  { method: "POST", path: "/api/plugins/automation/update", tier: "control" },
  { method: "POST", path: "/api/provider-auth/authorize", tier: "operate" },
  { method: "POST", path: "/api/provider-auth/device-code", tier: "operate" },
  { method: "POST", path: "/api/providers/test", tier: "operate" },
  { method: "POST", path: "/api/resources/reload", tier: "operate" },
  { method: "POST", path: "/api/resources/toggle", tier: "operate" },
  { method: "POST", path: "/api/resources/trust", tier: "operate" },
  { method: "POST", path: "/api/restart", tier: "operate" },
  { method: "POST", path: "/api/reveal-in-file-manager", tier: "operate" },
  { method: "POST", path: "/api/session/:id/abort", tier: "control" },
  { method: "POST", path: "/api/session/:id/archive", tier: "control" },
  { method: "POST", path: "/api/session/:id/attach-proposal", tier: "control" },
  { method: "POST", path: "/api/session/:id/detach-proposal", tier: "control" },
  { method: "POST", path: "/api/session/:id/extension-ui-response", tier: "control" },
  { method: "POST", path: "/api/session/:id/flow-control", tier: "control" },
  { method: "POST", path: "/api/session/:id/lifecycle", tier: "control" },
  { method: "POST", path: "/api/session/:id/model", tier: "control" },
  { method: "POST", path: "/api/session/:id/prompt", tier: "control" },
  { method: "POST", path: "/api/session/:id/rename", tier: "control" },
  { method: "POST", path: "/api/session/:id/resume", tier: "control" },
  { method: "POST", path: "/api/session/:id/shutdown", tier: "control" },
  { method: "POST", path: "/api/session/:id/thinking-level", tier: "control" },
  { method: "POST", path: "/api/session/:id/unarchive", tier: "control" },
  { method: "POST", path: "/api/session/spawn", tier: "control" },
  { method: "POST", path: "/api/shutdown", tier: "operate" },
  { method: "POST", path: "/api/tools/diagnostics", tier: "operate" },
  { method: "POST", path: "/api/tools/rescan", tier: "operate" },
  { method: "POST", path: "/api/tunnel-connect", tier: "operate" },
  { method: "POST", path: "/api/tunnel-disconnect", tier: "operate" },
  { method: "POST", path: "/api/tunnel-reserved-name", tier: "operate" },
  { method: "POST", path: "/api/tunnel/enroll", tier: "operate" },
  { method: "POST", path: "/api/ws-ticket", tier: "operate" },
  { method: "PUT", path: "/api/config", tier: "operate" },
  { method: "PUT", path: "/api/kb/config", tier: "operate" },
  { method: "PUT", path: "/api/mcp-client/servers/:name", tier: "operate" },
  { method: "PUT", path: "/api/mcp-client/servers/:name/disabled", tier: "operate" },
  { method: "PUT", path: "/api/mcp-client/settings", tier: "operate" },
  { method: "PUT", path: "/api/openspec/groups/assignments", tier: "control" },
  { method: "PUT", path: "/api/openspec/groups/change-order", tier: "control" },
  { method: "PUT", path: "/api/pi-retry", tier: "control" },
  { method: "PUT", path: "/api/plugins/blackhole/config", tier: "operate" },
  { method: "PUT", path: "/api/plugins/hermes-memory/config", tier: "operate" },
  { method: "PUT", path: "/api/provider-auth/api-key", tier: "operate" },
  { method: "PUT", path: "/api/providers", tier: "operate" },
  { method: "PUT", path: "/api/tools/:name", tier: "operate" },
];

const TIER_BY_ROUTE = new Map<string, Tier>(
  ROUTE_TIERS.map((e) => [`${e.method} ${e.path}`, e.tier]),
);

/**
 * Required tier for a REST route pattern. Unlisted → `operate` (fail closed).
 */
export function routeTier(method: string, path: string): Tier {
  return TIER_BY_ROUTE.get(`${method.toUpperCase()} ${path}`) ?? "operate";
}

/** Whether the map has an explicit entry for a route (completeness check). */
export function hasRouteTier(method: string, path: string): boolean {
  return TIER_BY_ROUTE.has(`${method.toUpperCase()} ${path}`);
}
